baseurl = "https://eclipse.dev/rcptt"
DefaultContentLanguage = "en"
title = "The Community for Open Innovation and Collaboration"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The Eclipse Foundation provides our global community of individuals and organizations with a mature, scalable, and business-friendly environment for open source software collaboration and innovation."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse", "project", "plug-ins", "plugins", "java", "ide", "swt", "refactoring", "free java ide", "tools", "platform", "open source", "development environment", "development", "ide"]
  news_count = 3
  gcse = "011805775785170369411:p3ec0igo0qq"
  gcse_result_url = "https://www.eclipse.org/home/search/"
  header_wrapper_class = "header_wrapper_class"
  call_for_action_text = "Download"
  call_for_action_url = "//eclipse.org/download/"
  call_for_action_icon = "fa-download"
  layout_style = "astro"
  hide_ad = false
  featured_content_publish_target = "eclipse_org"
  sidebar_layout = "default"
  RCPTTRELEASE = "2.5.5"
  RCPTTNIGHTLYVERSION = "2.6.0"
# js = "js/main.js"
# styles = ""
# logo = ""
# favicon = ""
# share_img = ""
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
# projects_working_group = ""
# show_events = true
# table_classes = "table table-bordered"
# hide_cfa_same_page = true
# show_collapsible_menu = true

[taxonomies]
  tag = 'tags'

[Author]
  name = "Vasili Gulevich"
  email = "vasili.gulevich@xored.com"
  linkedin = "vasiligulevich"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.sidebar]]
  name = "Home"
  url = "/"
  weight = 1
  identifier = "home"

# Uncomment [[menu.main]] to hide the default EF menu
# or to define your own menu links.

# [[menu.main]]